version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plant-leaf-analyzer
    ports:
      - "80:80"  # Updated to map host port 80 to container port 80
    volumes:
      - .:/app
      - ./static:/app/static
      - ./templates:/app/templates
      - ./uploads:/app/uploads
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - plant-leaf-network

networks:
  plant-leaf-network:
    driver: bridge